-- =========================================================
-- 1. ROLE AND WAREHOUSE
-- =========================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS EXAM_ETL_ROLE;

GRANT ROLE EXAM_ETL_ROLE TO ROLE SYSADMIN;

GRANT ROLE EXAM_ETL_ROLE TO USER BANASTASOV;

CREATE WAREHOUSE IF NOT EXISTS EXAM_ETL_WAREHOUSE
    WAREHOUSE_TYPE = STANDARD
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
;

GRANT USAGE
    ON WAREHOUSE EXAM_ETL_WAREHOUSE
    TO ROLE EXAM_ETL_ROLE;


GRANT OPERATE
    ON WAREHOUSE EXAM_ETL_WAREHOUSE
    TO ROLE EXAM_ETL_ROLE;


-- =========================================================
-- 2. DATABASE AND SCHEMAS
-- =========================================================

CREATE DATABASE IF NOT EXISTS EXAM_EX;

CREATE SCHEMA IF NOT EXISTS EXAM_EX.CLEANSED_LAYER;
CREATE SCHEMA IF NOT EXISTS EXAM_EX.BUSINESS_LAYER;
CREATE SCHEMA IF NOT EXISTS EXAM_EX.PRESENTATION_LAYER;

GRANT USAGE
    ON DATABASE EXAM_EX
    TO ROLE EXAM_ETL_ROLE;

GRANT USAGE
    ON ALL SCHEMAS IN DATABASE EXAM_EX
    TO ROLE EXAM_ETL_ROLE;

GRANT CREATE TABLE
    ON SCHEMA EXAM_EX.CLEANSED_LAYER
    TO ROLE EXAM_ETL_ROLE;

GRANT CREATE STAGE
    ON SCHEMA EXAM_EX.CLEANSED_LAYER
    TO ROLE EXAM_ETL_ROLE;

GRANT CREATE FILE FORMAT
    ON SCHEMA EXAM_EX.CLEANSED_LAYER
    TO ROLE EXAM_ETL_ROLE;

GRANT CREATE TABLE
    ON SCHEMA EXAM_EX.BUSINESS_LAYER
    TO ROLE EXAM_ETL_ROLE;

GRANT CREATE VIEW
    ON SCHEMA EXAM_EX.PRESENTATION_LAYER
    TO ROLE EXAM_ETL_ROLE;

GRANT CREATE MATERIALIZED VIEW
    ON SCHEMA EXAM_EX.PRESENTATION_LAYER
    TO ROLE EXAM_ETL_ROLE;

USE ROLE EXAM_ETL_ROLE;
USE WAREHOUSE EXAM_ETL_WAREHOUSE;
USE DATABASE EXAM_EX;


-- =========================================================
-- 3. FILE FORMAT AND STAGE
-- =========================================================

CREATE OR REPLACE FILE FORMAT CLEANSED_LAYER.PARQUET_FILE_FORMAT
    TYPE = PARQUET
    USE_LOGICAL_TYPE = TRUE
;


CREATE OR REPLACE STAGE PROCESSED_S3_STAGE
    URL = 's3://datawarehouse-etl-softuni/regular-exam/transformed-data/'
    CREDENTIALS = (
        AWS_KEY_ID = ''
        AWS_SECRET_KEY = ''
    )
    FILE_FORMAT = CLEANSED_LAYER.PARQUET_FILE_FORMAT;


LIST @CLEANSED_LAYER.PROCESSED_S3_STAGE;


-- =========================================================
-- 4. CLEANSED LAYER TABLES
-- =========================================================

CREATE OR REPLACE TABLE CLEANSED_LAYER.SALES_CLEAN (
    SALES_ID INTEGER,
    PRODUCT_ID INTEGER,
    REGION STRING,
    QTY INTEGER,
    PRICE DECIMAL(10, 2),
    TIME_STAMP DATETIME,
    DISCOUNT_PERCENTAGE DECIMAL(3, 2),
    ORDER_STATUS STRING
);


CREATE OR REPLACE TABLE CLEANSED_LAYER.PRODUCT_CLEAN (
    PRODUCT_ID INTEGER,
    CATEGORY STRING,
    BRAND STRING,
    RATING DECIMAL(3, 2),
    IN_STOCK BOOLEAN,
    LAUNCH_DATE DATETIME
);


CREATE OR REPLACE TABLE CLEANSED_LAYER.SALES_SUMMARY (
    SALES_ID INTEGER,
    PRODUCT_ID INTEGER,
    REGION STRING,
    QTY INTEGER,
    PRICE DECIMAL(10, 2),
    TIME_STAMP DATETIME,
    DISCOUNT_PERCENTAGE DECIMAL(3, 2),
    ORDER_STATUS STRING,
    CATEGORY STRING,
    BRAND STRING,
    RATING DECIMAL(3, 2),
    IN_STOCK BOOLEAN,
    LAUNCH_DATE DATETIME,
    DISCOUNT_AMOUNT DECIMAL(10, 2),
    TOTAL_REVENUE DECIMAL(10, 2)
);


-- =========================================================
-- 5. BUSINESS LAYER STAR SCHEMA
-- =========================================================

CREATE OR REPLACE TABLE BUSINESS_LAYER.DIM_DATE AS
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(TIME_STAMP, 'YYYYMMDD')) AS DATE_KEY,
    CAST(TIME_STAMP AS DATE) AS FULL_DATE,
    YEAR(TIME_STAMP) AS YEAR,
    QUARTER(TIME_STAMP) AS QUARTER,
    MONTH(TIME_STAMP) AS MONTH,
    MONTHNAME(TIME_STAMP) AS MONTH_NAME,
    DAY(TIME_STAMP) AS DAY_OF_MONTH,
    DAYNAME(TIME_STAMP) AS DAY_NAME
FROM CLEANSED_LAYER.SALES_CLEAN;


SELECT *
FROM BUSINESS_LAYER.DIM_DATE;

CREATE OR REPLACE TABLE BUSINESS_LAYER.DIM_PRODUCT AS
SELECT DISTINCT
    PRODUCT_ID,
    CATEGORY,
    BRAND,
    RATING,
    IN_STOCK,
    LAUNCH_DATE
FROM CLEANSED_LAYER.PRODUCT_CLEAN;


SELECT *
FROM BUSINESS_LAYER.DIM_PRODUCT;

CREATE OR REPLACE TABLE BUSINESS_LAYER.FACT_SALES AS
SELECT
    SALES_ID,
    PRODUCT_ID,
    TO_NUMBER(TO_CHAR(TIME_STAMP, 'YYYYMMDD')) AS DATE_KEY,
    REGION,
    QTY,
    PRICE,
    DISCOUNT_PERCENTAGE,
    DISCOUNT_AMOUNT,
    TOTAL_REVENUE,
    ORDER_STATUS
FROM CLEANSED_LAYER.SALES_SUMMARY;

SELECT *
FROM BUSINESS_LAYER.FACT_SALES;


-- =========================================================
-- 6. MATERIALIZED VIEWS
-- =========================================================

CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_REVENUE_BY_REGION AS
SELECT
    REGION,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE,
    SUM(QTY) AS TOTAL_QUANTITY,
    COUNT(*) AS SALES_COUNT
FROM BUSINESS_LAYER.FACT_SALES
GROUP BY REGION;


SELECT *
FROM PRESENTATION_LAYER.MV_REVENUE_BY_REGION
ORDER BY TOTAL_REVENUE DESC;


CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_SALES_BY_REGION AS
SELECT
    REGION,
    YEAR(TIME_STAMP) AS SALES_YEAR,
    MONTH(TIME_STAMP) AS SALES_MONTH,
    SUM(QTY) AS TOTAL_QUANTITY,
    COUNT(*) AS TOTAL_SALES,
    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_AMOUNT,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_SUMMARY
GROUP BY
    REGION,
    SALES_YEAR,
    SALES_MONTH;

SELECT *
FROM PRESENTATION_LAYER.MV_SALES_BY_REGION
ORDER BY SALES_YEAR, SALES_MONTH;


CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_TOP_PRODUCTS_BY_REVENUE AS
SELECT
    PRODUCT_ID,
    CATEGORY,
    BRAND,
    SUM(QTY) AS TOTAL_QUANTITY,
    COUNT(*) AS TOTAL_SALES,
    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_AMOUNT,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_SUMMARY
GROUP BY
    PRODUCT_ID,
    CATEGORY,
    BRAND;


SELECT *
FROM PRESENTATION_LAYER.MV_TOP_PRODUCTS_BY_REVENUE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_REVENUE_TREND AS
SELECT
    CAST(TIME_STAMP AS DATE) AS SALES_DATE,
    SUM(QTY) AS TOTAL_QUANTITY,
    COUNT(*) AS TOTAL_SALES,
    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_AMOUNT,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_SUMMARY
GROUP BY
    SALES_DATE;

SELECT *
FROM PRESENTATION_LAYER.MV_REVENUE_TREND
ORDER BY SALES_DATE;


CREATE OR REPLACE MATERIALIZED VIEW PRESENTATION_LAYER.MV_CATEGORY_PERFORMANCE AS
SELECT
    CATEGORY,
    SUM(QTY) AS TOTAL_QUANTITY,
    COUNT(*) AS TOTAL_SALES,
    AVG(PRICE) AS AVG_PRICE,
    AVG(RATING) AS AVG_RATING,
    SUM(DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_AMOUNT,
    SUM(TOTAL_REVENUE) AS TOTAL_REVENUE
FROM CLEANSED_LAYER.SALES_SUMMARY
GROUP BY
    CATEGORY;

SELECT *
FROM PRESENTATION_LAYER.MV_CATEGORY_PERFORMANCE;